export const INIT_DATA = 'INIT_DATA';
export const SET_ORIGINAL_JUDGING = 'SET_ORIGINAL_JUDGING';
export const SET_NEW_JUDGING = 'SET_NEW_JUDGING';

export const SELECT_FOR_EDITING = 'SELECT_FOR_EDITING';
export const SAVE = 'SAVE';
