export const SET_INITIALIZED = 'SET_INITIALIZED';

export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_CONTESTS = 'UPDATE_CONTESTS';
export const UPDATE_TEAMS = 'UPDATE_TEAMS';
